#!/usr/bin/env python

# Take a cDNA csv file and return a table with the RNA features.

# Written by Arnold Franz AKE
#aerod7710@gmail.com in April 2018
#@UMR7216 Paris Diderot

# -*- coding: utf-8 *-*-

#Loading packages
from multiprocessing import Pool, Process
import numpy as np
import pandas as pd
import math
import re
import sys
import subprocess
import rnaFeaturesLib
import argparse


#parser
parser = argparse.ArgumentParser(description = "Getting Features from a cDNAtable")
#Positionnal Arguments
parser.add_argument('cdnaTable_Pathway', metavar = "Source", type = str, help = 'Pathway to the cDna_table')
parser.add_argument('Output_FeaturesTab_Pathway', nargs="?", default = sys.stdout, metavar = "Output", type = str,
 help = 'Pathway to the cdnaFeaturesTable ; by default -> returning in the Stdout')

args = parser.parse_args()



#Loading Data
cdna = pd.read_csv(args.cdnaTable_Pathway)

#deleting NaN_Rows
cdna.dropna().shape #(17485,15)
cdna = cdna.dropna()
cdna = cdna.iloc[:200,:]
cdna = cdna.reset_index()

#P3utr_Len
#p3len = cdna['p3end']-cdna['p3start']
#utr3_len = pd.DataFrame(p3len, columns = ['utr3_len']).astype(int)
utr3_len = pd.DataFrame(rnaFeaturesLib.writeP3utr_fa(cdna), columns = ['utr3_len']).astype(int) #saving p3utrDEMO.fasta


#P5utr length
#p5len = cdna['p5end']-cdna['p5start']
#utr5_len = pd.DataFrame(p5len, columns = ['utr5_len']).astype(int)
utr5_len = pd.DataFrame(rnaFeaturesLib.writeP5utr_fa(cdna),columns = ['utr5_len']).astype(int) #saving p5utrDEMO.fasta


#Kozak_Context # TODO perhaps we will want to keep the Kozak sequence itself not only the context.
res = rnaFeaturesLib.getKozak(cdna, 10, 20)
kozak = res[0]
kozakseq = res[1]
contKozak = pd.DataFrame(kozak, columns = ['contextKozak'])	#(17485)    #Kozak_Context
sequKozak = pd.DataFrame(kozakseq, columns = ['sequenceKozak'])         #Kozak_Sequence

#get_uORF
uORFs = pd.Series(rnaFeaturesLib.get_uORF(cdna))

#get_dORF
dORFs = pd.Series(rnaFeaturesLib.get_dORF(cdna))


#Get_Folding Energy
#P5UTR
input_p5utr=open("../results/p5utrDEMO.fasta", "r+")   #recuperation fichier sotcke precedemment
input_p3utr=open("../results/p3utrDEMO.fasta", "r+")
rnaFeaturesLib.RNAfold_calcul(input_p5utr,"../results/mfep5.txt")
rnaFeaturesLib.RNAfold_calcul(input_p3utr,"../results/mfep3.txt")
p5mfe = rnaFeaturesLib.getFoldingEnergy("../results/mfep5.txt",cdna)
p3mfe = rnaFeaturesLib.getFoldingEnergy("../results/mfep3.txt",cdna)
input_p3utr.close()
input_p5utr.close()

#Concatenation des variables
features_tab = cdna.loc[:,['geneid','trid']]
features_tab['p3len'] = utr3_len
features_tab['p3mfe'] = p3mfe
features_tab['p5len'] = utr5_len
features_tab['p5mfe'] = p5mfe
features_tab['uORFs'] = uORFs
features_tab['dORFs'] = dORFs
features_tab['Kozak_Context'] = contKozak
features_tab['Kozak_sequence'] = sequKozak



#Sauvegarde
features_tab.to_csv(args.Output_FeaturesTab_Pathway, sep="\t", index = False)
